# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-16 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0003_auto_20170411_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Contest Category',
                'verbose_name_plural': 'Contest Categories',
                'proxy': True,
                'indexes': [],
            },
            bases=('blog.blogcategory',),
        ),
        migrations.CreateModel(
            name='ContestPost',
            fields=[
            ],
            options={
                'verbose_name': 'Contest',
                'verbose_name_plural': 'Contests',
                'proxy': True,
                'indexes': [],
            },
            bases=('blog.blogpost',),
        ),
    ]
