# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-19 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displayedproduct',
            name='link',
        ),
        migrations.AddField(
            model_name='displayedproduct',
            name='product_description',
            field=models.TextField(default='This is the product description', help_text='Brief description of the product', max_length=200, verbose_name='Description'),
        ),
    ]
