# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-16 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170411_0504'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContestPost',
        ),
        migrations.CreateModel(
            name='ContestPost',
            fields=[
                ('blogpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.BlogPost')),
            ],
            options={
                'verbose_name': 'Contest',
                'verbose_name_plural': 'Contests',
            },
            bases=('blog.blogpost',),
        ),
    ]
