# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-16 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210116_1117'),
        ('main', '0002_auto_20210116_1117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContestCategory',
        ),
        migrations.CreateModel(
            name='ContestCategory',
            fields=[
                ('blogcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.BlogCategory')),
            ],
            options={
                'verbose_name': 'Contest Category',
                'verbose_name_plural': 'Contest Categories',
            },
            bases=('blog.blogcategory',),
        ),
    ]
